### ISSUE TITLE
Issue installing phpmyadmin

### ISSUE THREAD

**Issue by carlosmq** [lukearmstrong/localhost#7]
Hi Luke,
I followed the tutorial in this repository https://lukearmstrong.github.io/2016/12/setup-apache-mysql-php-homebrew-macos-sierra/ and all worked very well, but (there's always a but, jajaja), I installed  phpmyadmin and I can't see it , I mean, when I go to localhost/phpmyadmin I only see "Page not found". Then I saw this error in apache error_log:

`[Mon Sep 11 11:39:55.729374 2017] [proxy_fcgi:error] [pid 81356] [client 127.0.0.1:57108] AH01071: Got error 'Primary script unknown\n'
So, I don't know where the error is, if there is one.`

Could you help me, pleas?
Regards,
Carlos.

**Comment by lukearmstrong** [comment]
Sorry, I don't know what could be causing that error or how to fix it.

I suggest you use Sequel Pro until you can figure it out (it's free!) http://www.sequelpro.com

**Comment by carlosmq** [comment]
Ok, I'll try it.
